package Form;

import Koneksi_DB.koneksinya;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jerni juntak
 */
public class Menu_Utama extends javax.swing.JFrame {
    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tktkunci = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CLOSE = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemuser = new javax.swing.JMenuItem();
        SIMPAN1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        gambar2 = new javax.swing.JMenuItem();
        SIMPAN2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        SIMPAN3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        SIMPAN4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Apotik V.1 Beta");
        setBackground(new java.awt.Color(255, 153, 255));
        setMaximumSize(new java.awt.Dimension(214748364, 214748364));
        setResizable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search 24 h p8.png"))); // NOI18N
        jButton1.setText("CARI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tktkunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tktkunciActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Produk");
        jLabel1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Browser Stop 24 h p8.png"))); // NOI18N
        CLOSE.setText("CLOSE");
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image1.jpg"))); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(250, 32767));
        jMenu1.setPreferredSize(new java.awt.Dimension(200, 139));

        itemuser.setText("gambar 1");
        itemuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemuserActionPerformed(evt);
            }
        });
        jMenu1.add(itemuser);

        SIMPAN1.setText("SIMPAN");
        SIMPAN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPAN1ActionPerformed(evt);
            }
        });
        jMenu1.add(SIMPAN1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image2.jpg"))); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(250, 32767));
        jMenu2.setPreferredSize(new java.awt.Dimension(200, 206));

        gambar2.setText("Gambar 2");
        gambar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gambar2ActionPerformed(evt);
            }
        });
        jMenu2.add(gambar2);

        SIMPAN2.setText("SIMPAN");
        SIMPAN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPAN2ActionPerformed(evt);
            }
        });
        jMenu2.add(SIMPAN2);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image3'.jpg"))); // NOI18N
        jMenu3.setMaximumSize(new java.awt.Dimension(250, 32767));
        jMenu3.setPreferredSize(new java.awt.Dimension(200, 222));

        jMenuItem5.setText("Gambar 3");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        SIMPAN3.setText("SIMPAN");
        SIMPAN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPAN3ActionPerformed(evt);
            }
        });
        jMenu3.add(SIMPAN3);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image4.jpg"))); // NOI18N
        jMenu4.setMaximumSize(new java.awt.Dimension(300, 32767));
        jMenu4.setPreferredSize(new java.awt.Dimension(200, 203));

        jMenuItem6.setText("GAMBAR 4");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        SIMPAN4.setText("SIMPAN");
        SIMPAN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPAN4ActionPerformed(evt);
            }
        });
        jMenu4.add(SIMPAN4);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Tentang");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/About.png"))); // NOI18N
        jMenuItem8.setText("About");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel1)
                        .addGap(137, 137, 137)
                        .addComponent(tktkunci, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(CLOSE)))
                .addContainerGap(614, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tktkunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CLOSE)
                .addContainerGap(757, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemuserActionPerformed

    }//GEN-LAST:event_itemuserActionPerformed

    private void SIMPAN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPAN2ActionPerformed
   Simpan2();
    }//GEN-LAST:event_SIMPAN2ActionPerformed

    private void gambar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gambar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gambar2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void SIMPAN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPAN1ActionPerformed

        Simpan1();
        
    }//GEN-LAST:event_SIMPAN1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tktkunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tktkunciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tktkunciActionPerformed

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void SIMPAN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPAN4ActionPerformed
        // TODO add your handling code here:
        Simpan4();
    }//GEN-LAST:event_SIMPAN4ActionPerformed

    private void SIMPAN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPAN3ActionPerformed
        Simpan3();        // TODO add your handling code here:
    }//GEN-LAST:event_SIMPAN3ActionPerformed
     
    ResultSet Rs;  
  public void cari(){
       DefaultTableModel tabel = new DefaultTableModel();
       tabel.addColumn("ID");
       tabel.addColumn("NAMA");
       tabel.addColumn("Tanggal Akses");
       String kunci = tktkunci.getText();
       try{
           Statement state  = koneksinya.GetConnection().createStatement();
              Rs = state.executeQuery("Select * from data where id = '"+kunci+"'");
           while(Rs.next()){
               tabel.addRow(new Object[]{
                   Rs.getString(1),
                   Rs.getString(2),
                   Rs.getString(3),              
               });
               jTable1.setModel(tabel);
           }
           tktkunci.setText(null);
           state.close();
           Rs.close();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan !");
       }
    }

    public void Simpan1(){
        String id = "1";
        String nama = "gambar 1";
        String tanggal = "1/9/2022";
        
        try{
            Statement state  = koneksinya.GetConnection().createStatement();
            state.executeUpdate("insert into data values ('"+id+"','"+nama+"','"+tanggal+"')");
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan !");
           // Reset();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data Gagal Disimpan !");
        }
    }
        public void Simpan2(){
        String id = "2";
        String nama = "gambar 2";
        String tanggal = "1/9/2022";
        
        try{
            Statement state  = koneksinya.GetConnection().createStatement();
            state.executeUpdate("insert into data values ('"+id+"','"+nama+"','"+tanggal+"')");
           
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan !");
          
        }
        catch(Exception e){
         //   JOptionPane.showMessageDialog(this, "Data Gagal Disimpan !");
        }
    }
               public void Simpan3(){
        String id = "3";
        String nama = "gambar 3";
        String tanggal = "1/3/2022";
        
        try{
            Statement state  = koneksinya.GetConnection().createStatement();
            state.executeUpdate("insert into data values ('"+id+"','"+nama+"','"+tanggal+"')");
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan !");
           // Reset();
           // state.close();
        }
        catch(Exception e){
         //   JOptionPane.showMessageDialog(this, "Data Gagal Disimpan !");
        }
    }
                      public void Simpan4(){
        String id = "4";
        String nama = "gambar 4";
        String tanggal = "1/9/2022";
        
        try{
            Statement state  = koneksinya.GetConnection().createStatement();
            state.executeUpdate("insert into data values ('"+id+"','"+nama+"','"+tanggal+"')");
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan !");

        }
        catch(Exception e){
         //   JOptionPane.showMessageDialog(this, "Data Gagal Disimpan !");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLOSE;
    private javax.swing.JMenuItem SIMPAN1;
    private javax.swing.JMenuItem SIMPAN2;
    private javax.swing.JMenuItem SIMPAN3;
    private javax.swing.JMenuItem SIMPAN4;
    private javax.swing.JMenuItem gambar2;
    private javax.swing.JMenuItem itemuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tktkunci;
    // End of variables declaration//GEN-END:variables
}
